"""Settings"""

OTEL_SERVICE_NAME = "dotflow"
OTEL_METRICS_EXPORT_INTERVAL_MILLIS = "5000"
OTEL_EXPORTER_OTLP_ENDPOINT = "0.0.0.0:4317"
OTEL_EXPORTER_OTLP_INSECURE = "true"
OTEL_PYTHON_LOG_CORRELATION = "true"
OTEL_PYTHON_LOG_FORMAT = "%(asctime)s - %(levelname)s [%(name)s]: %(message)s"
OTEL_PYTHON_LOG_LEVEL = "20"
OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED = "true"
OTEL_PYTHON_LOGGING_SCHEDULE_DELAY_MILLIS = "5000"
OTEL_PYTHON_EXCLUDED_URLS = "client/.*/info,healthcheck"
OTEL_PYTHON_URLLIB3_EXCLUDED_URLS = "client/.*/info"
OTEL_PYTHON_REQUESTS_EXCLUDED_URLS = "healthcheck"


_env_to_name = {
    OTEL_SERVICE_NAME: "OTEL_SERVICE_NAME",
    OTEL_METRICS_EXPORT_INTERVAL_MILLIS: "OTEL_METRICS_EXPORT_INTERVAL_MILLIS",
    OTEL_EXPORTER_OTLP_ENDPOINT: "OTEL_EXPORTER_OTLP_ENDPOINT",
    OTEL_EXPORTER_OTLP_INSECURE: "OTEL_EXPORTER_OTLP_INSECURE",
    OTEL_PYTHON_LOG_CORRELATION: "OTEL_PYTHON_LOG_CORRELATION",
    OTEL_PYTHON_LOG_FORMAT: "OTEL_PYTHON_LOG_FORMAT",
    OTEL_PYTHON_LOG_LEVEL: "OTEL_PYTHON_LOG_LEVEL",
    OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED",
    OTEL_PYTHON_LOGGING_SCHEDULE_DELAY_MILLIS: "OTEL_PYTHON_LOGGING_SCHEDULE_DELAY_MILLIS",
    OTEL_PYTHON_EXCLUDED_URLS: "OTEL_PYTHON_EXCLUDED_URLS",
    OTEL_PYTHON_URLLIB3_EXCLUDED_URLS: "OTEL_PYTHON_URLLIB3_EXCLUDED_URLS",
    OTEL_PYTHON_REQUESTS_EXCLUDED_URLS: "OTEL_PYTHON_REQUESTS_EXCLUDED_URLS",
}

_name_to_env = {
    "OTEL_SERVICE_NAME": OTEL_SERVICE_NAME,
    "OTEL_METRICS_EXPORT_INTERVAL_MILLIS": OTEL_METRICS_EXPORT_INTERVAL_MILLIS,
    "OTEL_EXPORTER_OTLP_ENDPOINT": OTEL_EXPORTER_OTLP_ENDPOINT,
    "OTEL_EXPORTER_OTLP_INSECURE": OTEL_EXPORTER_OTLP_INSECURE,
    "OTEL_PYTHON_LOG_CORRELATION": OTEL_PYTHON_LOG_CORRELATION,
    "OTEL_PYTHON_LOG_FORMAT": OTEL_PYTHON_LOG_FORMAT,
    "OTEL_PYTHON_LOG_LEVEL": OTEL_PYTHON_LOG_LEVEL,
    "OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED": OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED,
    "OTEL_PYTHON_LOGGING_SCHEDULE_DELAY_MILLIS": OTEL_PYTHON_LOGGING_SCHEDULE_DELAY_MILLIS,
    "OTEL_PYTHON_EXCLUDED_URLS": OTEL_PYTHON_EXCLUDED_URLS,
    "OTEL_PYTHON_URLLIB3_EXCLUDED_URLS": OTEL_PYTHON_URLLIB3_EXCLUDED_URLS,
    "OTEL_PYTHON_REQUESTS_EXCLUDED_URLS": OTEL_PYTHON_REQUESTS_EXCLUDED_URLS,
}
